CREATE TABLE GRADES (
 GradeId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
 StdId INT NULL FOREIGN KEY REFERENCES student(StdId),
 CourseId INT NULL FOREIGN KEY REFERENCES course(CourseId),	
 Grade INT NULL,	 
);